const data = [
{ Name: "Product 1", id: 1, Shelf: "A", Slot: 1, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-dasani.svg" },
{ Name: "Product 2", id: 2, Shelf: "A", Slot: 2, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 3", id :3, Shelf: "A", Slot: 3, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 4", id :4, Shelf: "A", Slot: 4, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 5", id :5, Shelf: "A", Slot: 5, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 6", id :6, Shelf: "A", Slot: 6, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-diet.svg" },
{ Name: "Product 1", id :7, Shelf: "B", Slot: 1, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-diet.svg" },
{ Name: "Product 2", id :8, Shelf: "B", Slot: 2, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-diet.svg" },
{ Name: "Product 3", id : 9, Shelf: "B", Slot: 3, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-diet.svg" },
{ Name: "Product 4", id :10, Shelf: "B", Slot: 4, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-diet.svg" },
{ Name: "Product 5", id :11, Shelf: "B", Slot: 5, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-diet.svg" },
{ Name: "Product 6", id :12, Shelf: "B", Slot: 6, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-diet.svg" },
{ Name: "Product 7", id:13 , Shelf: "c", Slot: 1, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 7", id:14 , Shelf: "c", Slot: 2, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 7", id:15 , Shelf: "c", Slot: 3, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 7", id:16 , Shelf: "c", Slot: 4, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 7", id:17 , Shelf: "c", Slot: 5, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 7", id:18 , Shelf: "c", Slot: 6, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 7", id:19 , Shelf: "c", Slot: 1, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 7", id:20 , Shelf: "D", Slot: 2, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 7", id:21 , Shelf: "D", Slot: 3, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 7", id:22 , Shelf: "D", Slot: 4, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 7", id:23 , Shelf: "D", Slot: 5, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
{ Name: "Product 7", id:24 , Shelf: "D", Slot: 6, Price: 250, Stock: 5, ImageURL: "http://giovanni.io/coke/graphics/bottles/bottle-coke.svg" },
]